name: Go module upgrade
on:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: 1.19.3
      - name: Checkout codebase
        uses: actions/checkout@main

      - name: Start Setup Submodule
        run: |
          git submodule update --init
          git submodule update --recursive --remote
          cd web
          ln -sf ../translation translation
          cd ..
          ln -sf bin/build build
      - name: go
        run: |
          go mod tidy
          go get -u
          go mod download
      - name: Git push
        run: |
          git init
          git config --local user.name "dopaemon"
          git config --local user.email "polarisdp@gmail.com"
          git remote rm origin
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git gc --aggressive
          git add --all
          git commit -m "GoLang: Upgrade GoMod$(date +%Y%m%d%H%M)"
          git push -f -u origin main
